version: '3'
services:
db: 
image: 'postgres:latest'

environment:
POSTGRES_PASSWORD: root
POSTGRES_USER: postgres
POSTGRES_DB: ProjetoTypeorm
volumes:

-  ./pgdata:/var/lib/postgresql/data
ports: 
- "5432:5432"

app: 
  container_name: PRojetoType
  restart: always 
  build: .
  ports: 
    - "300:300"

    depends_on: 
      - db 